version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: feedbackhub
      POSTGRES_PASSWORD: feedbackhub
      POSTGRES_DB: feedbackhub
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
